name: gs CI

on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
       - name: Check out repository code
         uses: actions/checkout@v4
       - name: Setup Node.js v20
         uses: actions/setup-node@v4
         with:
           node-version: 20
       - name: Install JSLint
         run: npm install jslint
       - name: Run JSLint
         run: node jslint '*.gs'
         
